# Generated by Django 2.0.4 on 2019-02-06 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('documento', models.FileField(upload_to='uploads/user')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='uploads/admin')),
                ('nombre', models.CharField(max_length=70)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono1', models.IntegerField(max_length=10)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('cedula', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('clave', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Statico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('correo', models.EmailField(max_length=45)),
                ('telefono1', models.IntegerField(max_length=10)),
                ('telefono2', models.IntegerField(max_length=10)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=20)),
                ('salario', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='archivo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Empleado'),
        ),
    ]
