# Generated by Django 2.0.4 on 2019-02-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='documento',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='telefono1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statico',
            name='telefono1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statico',
            name='telefono2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='tipo',
            field=models.CharField(choices=[('HT', 'Medio Tiempo'), ('CT', 'Tiempo completo')], default='CT', max_length=20),
        ),
    ]
