# Generated by Django 2.0.4 on 2019-02-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190210_2350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statico',
            new_name='Estatico',
        ),
    ]
