# Generated by Django 2.0.4 on 2019-02-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190211_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='documento',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='documento',
            field=models.FileField(upload_to='media'),
        ),
    ]
