# Generated by Django 2.0.4 on 2019-02-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190211_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='nombre',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
