# Generated by Django 2.0.4 on 2019-02-12 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190211_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatico',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='estado',
            field=models.CharField(choices=[('rv', 'Revisado'), ('SR', 'Sin revisar')], default='SR', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('rv', 'Revisado'), ('SR', 'Sin revisar')], default='SR', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('UNO', 'Nombre de la Solicitud 1'), ('DOS', 'Nombre de la Solicitud 2'), ('TRES', 'Nombre de la Solicitud 3')], max_length=20),
        ),
    ]
