# Generated by Django 2.0.4 on 2019-02-18 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190211_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Guardado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Guardado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha de Guardado'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Sin revisar', 'Sin revisar'), ('En proceso', 'En proceso')], default='Sin revisar', max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha de Guardado'),
        ),
    ]
