# Generated by Django 2.0.4 on 2019-02-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190217_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatico',
            name='horario',
            field=models.CharField(default='9:30 A.M. a 6:30 P.M.', max_length=50),
            preserve_default=False,
        ),
    ]
