# Generated by Django 2.0.4 on 2019-02-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_estatico_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='texto',
            field=models.CharField(default='', max_length=500),
        ),
    ]
