# Generated by Django 2.0.4 on 2019-02-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_curriculum_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='curriculum',
            field=models.FileField(default='no_file', upload_to='media'),
        ),
    ]
