# Generated by Django 2.0.4 on 2019-02-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_empleado_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='archivo',
            name='tipo',
            field=models.CharField(choices=[('UNO', 'Nombre de la Solicitud 1'), ('DOS', 'Nombre de la Solicitud 2'), ('TRES', 'Nombre de la Solicitud 3')], default='UNO', max_length=70),
        ),
    ]
