# Generated by Django 2.0.4 on 2019-02-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190219_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='clave',
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(default='esta', max_length=150),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
