# Generated by Django 2.0.4 on 2019-02-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190219_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(default='no_image', upload_to='media'),
        ),
    ]
