# Generated by Django 2.0.4 on 2019-02-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_empleado_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='direccion',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajo',
            name='subtitulo',
            field=models.CharField(default='none', max_length=70),
            preserve_default=False,
        ),
    ]
