# Generated by Django 2.0.4 on 2019-02-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_trabajo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='enlace',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='tipo',
            field=models.CharField(choices=[('Medio Tiempo', 'Medio Tiempo'), ('Tiempo completo', 'Tiempo completo')], default='Tiempo completo', max_length=20),
        ),
    ]
