# Generated by Django 2.0.4 on 2019-02-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_empleado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='tipo',
            field=models.CharField(choices=[('Desprendible de pago', 'Nombre de la Solicitud 1'), ('Certificado de tabajo', 'Nombre de la Solicitud 2'), ('Certificado de trabajo', 'Nombre de la Solicitud 3')], default='Desprendible de pago', max_length=70),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('Desprendible de pago', 'Nombre de la Solicitud 1'), ('Certificado de tabajo', 'Nombre de la Solicitud 2'), ('Certificado de trabajo', 'Nombre de la Solicitud 3')], max_length=125),
        ),
    ]
