# Generated by Django 2.0.4 on 2019-02-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190222_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='tipo',
            field=models.CharField(choices=[('Desprendible de pago', 'Desprendible de pago'), ('Certificado de tabajo', 'Certificado de tabajo'), ('Certificado de EPS', 'Certificado de EPS')], default='Desprendible de pago', max_length=70),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('Desprendible de pago', 'Desprendible de pago'), ('Certificado de tabajo', 'Certificado de tabajo'), ('Certificado de EPS', 'Certificado de EPS')], max_length=125),
        ),
    ]
