# Generated by Django 2.0.4 on 2019-03-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190222_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='texto',
            field=models.TextField(default=''),
        ),
    ]
