# Generated by Django 2.0.4 on 2019-03-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190312_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatico',
            name='mision',
        ),
        migrations.RemoveField(
            model_name='estatico',
            name='vision',
        ),
    ]
