# Generated by Django 2.0.4 on 2019-03-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190313_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatico',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
